**SQL ASSIGNMENT**

**Daniel Maithya**

In [ ]:
#Importing the sqlite3 module and the panda library
import sqlite3
import pandas as pd

# Load datasets
athletes = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/athlete_events.csv")
regions = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/noc_regions.csv")
sales = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
sales = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')


# Connect to SQLite in-memory DB
conn = sqlite3.connect(":memory:")

# Write DataFrames to SQL tables
athletes.to_sql("athletes_table", conn, index=False, if_exists="replace")
regions.to_sql("regions_table", conn, index=False, if_exists="replace")
sales.to_sql("sales_table", conn, index=False, if_exists="replace")

4622

**Section 1**

The athletes dataset:

1. Top 5 total number of medals won by each country.

Visualizing the data held in the athletes table

In [ ]:
#Here I am viewing the date in the athletes table
pd.read_sql(
    """
    SELECT *
    FROM athletes_table
    """,
    conn
)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,None
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,None
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,None
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,None
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",None
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",None
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,None
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,None

Visualizing data held in the regions table

In [ ]:
#Here I am viewing the data held in the regions table
pd.read_sql(
    """
    SELECT *
    FROM regions_table
    """,
    conn
)

     NOC       region                 notes
0    AFG  Afghanistan                  None
1    AHO      Curacao  Netherlands Antilles
2    ALB      Albania                  None
3    ALG      Algeria                  None
4    AND      Andorra                  None
..   ...          ...                   ...
225  YEM        Yemen                  None
226  YMD        Yemen           South Yemen
227  YUG       Serbia            Yugoslavia
228  ZAM       Zambia                  None
229  ZIM     Zimbabwe                  None

[230 rows x 3 columns]

Grouping by country's that won gold and listing the top 5

In [ ]:
pd.read_sql(
    """
    SELECT r.region AS country, COUNT(a.medal) AS total_medals
    FROM athletes_table a
    JOIN regions_table r ON a.NOC = r.NOC
    WHERE a.Medal = 'Gold'
    GROUP BY country
    ORDER BY total_medals DESC
    LIMIT 5;
    """,
    conn
)

   country  total_medals
0      USA          2638
1   Russia          1599
2  Germany          1301
3       UK           678
4    Italy           575

2. Average age of athletes who won a Gold medal.

In [ ]:
pd.read_sql(
    """
    SELECT AVG(Age) AS avg_age_gold_medalists
    FROM athletes_table
    WHERE medal = 'Gold'
    """,
    conn
)

   avg_age_gold_medalists
0               25.901013

3. Distinct events in each sport

In [ ]:
pd.read_sql(
    """
    SELECT Sport, COUNT(DISTINCT Event) AS no_of_events
    FROM athletes_table
    GROUP BY Sport
    ORDER BY no_of_events DESC
    """,
    conn
)

            Sport  no_of_events
0        Shooting            83
1       Athletics            83
2        Swimming            55
3         Cycling            44
4         Sailing            38
..            ...           ...
61        Cricket             1
62  Basque Pelota             1
63       Baseball             1
64       Alpinism             1
65    Aeronautics             1

[66 rows x 2 columns]

4. All athletes from the United States (NOC = 'USA').

In [ ]:
pd.read_sql(
    """
    SELECT *
    FROM athletes_table
    WHERE NOC = 'USA'
    """,
    conn
)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,None
1,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,None
2,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,None
3,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,None
4,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18848,135458,Rami Zur,M,27.0,175.0,77.0,United States,USA,2004 Summer,2004,Summer,Athina,Canoeing,"Canoeing Men's Kayak Doubles, 500 metres",None
18849,135458,Rami Zur,M,31.0,175.0,77.0,United States,USA,2008 Summer,2008,Summer,Beijing,Canoeing,"Canoeing Men's Kayak Singles, 500 metres",None
18850,135458,Rami Zur,M,31.0,175.0,77.0,United States,USA,2008 Summer,2008,Summer,Beijing,Canoeing,"Canoeing Men's Kayak Singles, 1,000 metres",None
18851,135543,"Victor Andrew ""Vic"" Zwolak",M,25.0,175.0,64.0,United States,USA,1964 Summer,1964,Summer,Tokyo,Athletics,"Athletics Men's 3,000 metres Steeplechase",None
18852,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,None

5. Medals were awarded each year.

In [ ]:
pd.read_sql(
    """
    SELECT Year, COUNT(Medal) AS no_of_medals
    FROM athletes_table
    GROUP BY Year
    ORDER BY Year
    """,
    conn
)

    Year  no_of_medals
0   1896           143
1   1900           604
2   1904           486
3   1906           458
4   1908           831
5   1912           941
6   1920          1308
7   1924           962
8   1928           823
9   1932           739
10  1936          1025
11  1948           987
12  1952          1033
13  1956          1043
14  1960          1058
15  1964          1215
16  1968          1256
17  1972          1414
18  1976          1531
19  1980          1602
20  1984          1698
21  1988          1845
22  1992          2030
23  1994           331
24  1996          1842
25  1998           440
26  2000          2004
27  2002           478
28  2004          2001
29  2006           526
30  2008          2048
31  2010           520
32  2012          1941
33  2014           597
34  2016          2023

6. All athlete records where height or weight is missing.

In [ ]:
pd.read_sql(
    """
    SELECT *
    FROM athletes_table
    WHERE Height IS NULL OR Weight IS NULL
    """,
    conn
)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,None
1,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
2,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,None
3,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 4 x 100 metres Relay,None
4,10,"Einar Ferdinand ""Einari"" Aalto",M,26.0,NaN,NaN,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Swimming,Swimming Men's 400 metres Freestyle,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64258,135539,Marius Edmund Zwiller,M,18.0,NaN,NaN,France,FRA,1924 Summer,1924,Summer,Paris,Swimming,Swimming Men's 200 metres Breaststroke,None
64259,135542,Werner Zwingli,M,29.0,NaN,NaN,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,None
64260,135542,Werner Zwingli,M,29.0,NaN,NaN,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,None
64261,135552,Jan (Johann-) Zybert (Siebert-),M,20.0,NaN,NaN,Poland,POL,1928 Summer,1928,Summer,Amsterdam,Cycling,"Cycling Men's Team Pursuit, 4,000 metres",None
64262,135561,Frantiek Zyka,M,26.0,NaN,NaN,Czechoslovakia,TCH,1928 Summer,1928,Summer,Amsterdam,Athletics,Athletics Men's Marathon,None

7. Replacing the missing height with the average athlete height.

In [ ]:
pd.read_sql(
    """
    SELECT *, COALESCE(height, (
        SELECT AVG(height)
        FROM athletes_table
        WHERE height IS NOT NULL
    )) AS new_height
    FROM athletes_table;
    """,
    conn
)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,new_height
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,None,180.00000
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,None,170.00000
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,None,175.33897
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,175.33897
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,None,185.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,None,179.00000
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",None,176.00000
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",None,176.00000
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,None,185.00000
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,None,185.00000

The sales dataset: where necessary, use the key word CAST to remove the $ sign from the item_price

  Visualizing data held in the sales dataset

In [ ]:
pd.read_sql(
    """
    SELECT *
    FROM sales_table
    """,
    conn
)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,None,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,None,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

8. Total sales value per item.

In [ ]:
pd.read_sql(
    """
    SELECT item_name, SUM(item_price) AS total_sales_value
    FROM sales_table
    GROUP BY item_name
    """,
    conn
)

                                item_name  total_sales_value
0                       6 Pack Soft Drink                0.0
1                           Barbacoa Bowl                0.0
2                        Barbacoa Burrito                0.0
3                   Barbacoa Crispy Tacos                0.0
4                     Barbacoa Salad Bowl                0.0
5                     Barbacoa Soft Tacos                0.0
6                           Bottled Water                0.0
7                                    Bowl                0.0
8                                 Burrito                0.0
9                             Canned Soda                0.0
10                      Canned Soft Drink                0.0
11                          Carnitas Bowl                0.0
12                       Carnitas Burrito                0.0
13                  Carnitas Crispy Tacos                0.0
14                         Carnitas Salad                0.0
15                    Carnitas Salad Bowl                0.0
16                    Carnitas Soft Tacos                0.0
17                           Chicken Bowl                0.0
18                        Chicken Burrito                0.0
19                   Chicken Crispy Tacos                0.0
20                          Chicken Salad                0.0
21                     Chicken Salad Bowl                0.0
22                     Chicken Soft Tacos                0.0
23                                  Chips                0.0
24           Chips and Fresh Tomato Salsa                0.0
25                    Chips and Guacamole                0.0
26      Chips and Mild Fresh Tomato Salsa                0.0
27     Chips and Roasted Chili Corn Salsa                0.0
28     Chips and Roasted Chili-Corn Salsa                0.0
29  Chips and Tomatillo Green Chili Salsa                0.0
30    Chips and Tomatillo Red Chili Salsa                0.0
31  Chips and Tomatillo-Green Chili Salsa                0.0
32    Chips and Tomatillo-Red Chili Salsa                0.0
33                           Crispy Tacos                0.0
34                                   Izze                0.0
35                       Nantucket Nectar                0.0
36                                  Salad                0.0
37                          Side of Chips                0.0
38                             Steak Bowl                0.0
39                          Steak Burrito                0.0
40                     Steak Crispy Tacos                0.0
41                            Steak Salad                0.0
42                       Steak Salad Bowl                0.0
43                       Steak Soft Tacos                0.0
44                            Veggie Bowl                0.0
45                         Veggie Burrito                0.0
46                    Veggie Crispy Tacos                0.0
47                           Veggie Salad                0.0
48                      Veggie Salad Bowl                0.0
49                      Veggie Soft Tacos                0.0

9. Top 5 records with the highest item_price.

In [ ]:
pd.read_sql (
    """
    SELECT *
    FROM sales_table
    ORDER BY item_price DESC
    LIMIT 5
    """,
    conn
)

,order_id,quantity,item_name,choice_description,item_price
0,250,1,Steak Salad Bowl,"[Fresh Tomato Salsa, Lettuce]",$9.39
1,576,1,Barbacoa Salad Bowl,[Roasted Chili Corn Salsa],$9.39
2,576,1,Barbacoa Salad Bowl,[Roasted Chili Corn Salsa],$9.39
3,738,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$9.39
4,756,1,Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$9.39

10. Number of unique customer orders available. (Assume each order_id is a customer.)

In [ ]:
pd.read_sql(
    """
    SELECT COUNT(DISTINCT order_id) AS unique_orders
    FROM sales_table
    """,
    conn
)

   unique_orders
0           1834

**Section 2**

Write one query for this section.

Find countries with high-performing athletes in the Olympics. Use at least JOIN, NESTED QUERY, CASE, and optionally WITH.

For each country:

Count the number of athletes who won at least one medal.
Determine the average age of those medalists.
Create a new column called performance:
- 'High' if average age is below 25
- 'Medium' if between 25 and 30
- 'Low' if above 30

In [ ]:
pd.read_sql(
    """
    WITH medalists AS (
        SELECT DISTINCT a.ID, a.name, a.age, r.region AS country
        FROM athletes_table a
        JOIN regions_table r ON a.NOC = r.NOC
        WHERE a.medal IS NOT NULL
    ),
    country_stats AS (
        SELECT
            country,
            COUNT(*) AS num_medalists,
            AVG(age) AS avg_age
        FROM medalists
        WHERE age IS NOT NULL
        GROUP BY country
    )
    SELECT
        country,
        num_medalists,
        ROUND(avg_age, 2) AS avg_age,
        CASE
            WHEN avg_age < 25 THEN 'High'
            WHEN avg_age BETWEEN 25 AND 30 THEN 'Medium'
            ELSE 'Low'
        END AS performance
    FROM country_stats
    ORDER BY num_medalists DESC
    LIMIT 20;
    """,
    conn
)

           country  num_medalists  avg_age performance
0              USA           4618    25.09      Medium
1           Russia           3398    25.40      Medium
2          Germany           3233    25.54      Medium
3               UK           1778    27.87      Medium
4           France           1446    27.61      Medium
5            Italy           1422    26.88      Medium
6           Sweden           1380    27.97      Medium
7           Canada           1231    26.00      Medium
8        Australia           1153    25.29      Medium
9          Hungary            990    26.42      Medium
10     Netherlands            928    26.40      Medium
11          Norway            870    27.69      Medium
12           China            849    23.36        High
13           Japan            783    24.44        High
14         Finland            771    27.36      Medium
15  Czech Republic            597    26.08      Medium
16     South Korea            576    23.59        High
17         Denmark            575    26.77      Medium
18     Switzerland            557    28.32      Medium
19         Romania            539    24.78        High